
name: Trigger Netlify Build
on:
  schedule:
    - cron: '* * * * 0'
jobs:
  build:
    environment: 'Netlify CRON action'
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }} 
